### ISSUE TITLE
JavaDoc

### ISSUE THREAD

**Issue by SemenMartynov** [ShuvalovPavel/json_validator#3]
Provide correct JavaDoc for your code.

**Comment by ShuvalovPavel** [comment]
https://github.com/ShuvalovPavel/json_validator/commit/6d2ed777e7c3acd4405197022de5970d2da4b78d
https://github.com/ShuvalovPavel/json_validator/commit/5af8463bf9fd0b1b20eafca6751e379ec5138b5e

**Comment by SemenMartynov** [comment]
No need to store JavaDoc in repo

**Comment by ShuvalovPavel** [comment]
https://github.com/ShuvalovPavel/json_validator/commit/ad917eceddecb65e2464cf344fc4c05fc5cd5851
