### ISSUE TITLE
Magic number

### ISSUE THREAD

**Issue by SemenMartynov** [ShuvalovPavel/json_validator#4]
Magic number in a code is the bad style.

https://github.com/ShuvalovPavel/json_validator/blob/1b318bbb4cdcd831197d57423b372746951d99d2/src/main/java/com/mycompany/json_validator/Main.java#L21

**Comment by ShuvalovPavel** [comment]
https://github.com/ShuvalovPavel/json_validator/commit/db57db1816bf98880c2d5630395232e56d328b6e

**Comment by SemenMartynov** [comment]
I would split the port and url.
